version: 2
general:
  branches:
    only:
     - master
jobs:
  build:
    docker: 
      - image: node:7.4.0
    working_directory: ~/connectedacademy
    steps:
      - checkout
      - run: npm install
      - run: npm run generate
      - add_ssh_keys
      - run: git config --global user.name "CircleCI"
      - run: git config --global user.email "info@connectedacademy.io"
      - run: git commit -am"[skip CI] AUTOBUILD"
      - run: git checkout gh-pages
      - run: git pull
      - run: git merge -X theirs master
      - run: git push origin HEAD:gh-pages