hashtag: "#wpca17"
starts: "2017-04-01T22:47:31-07:00"
ends: "2017-09-20T22:47:31-07:00"
accounts: 
  - tombartindale
langs:
  - en
about: about.md
info: info.md
classes:
  -
    dir: class1
    slug: evidence
    content:
      -
        url: intro.md
        slug: intro
      -
        slug: question1
        content_type: question
      -
        url: extra-pre-reading.md
        slug: prereading
      -
        url: class.md
        slug: liveclass
        schedule:
          -
            release_at: "2017-04-05T10:57:37+01:00"
            leadhub: true
            hub_id: "ams"
      -
        slug: question2
        content_type: question
      -
        url: deepdive.md
        slug: deepdive
      -
        url: extended.md
        slug: extended
      -
        slug: question3
        content_type: question
      -
        url: webinar.md
        slug: webinar
        schedule:
          -
            release_at: "2017-04-08T22:57:37-07:00"
      -
        content_type: question
      -
        url: whatnext.md
        slug: whatnext
  -
    dir: class2
    slug: interpretation
    content:
      -
        url: intro.md
        slug: intro
      -
        slug: question1
        content_type: question
      -
        url: extra-pre-reading.md
        slug: prereading
      -
        url: class.md
        slug: liveclass
        schedule:
          -
            release_at: "2017-04-10T10:57:37+01:00"
            leadhub: true
            hub_id: "ams"
      -
        slug: question2
        content_type: question
      -
        url: extended.md
        slug: extended
      -
        url: deepdive.md
        slug: deepdive
      -
        slug: question3
        content_type: question
      -
        url: webinar.md
        slug: webinar
        schedule:
          -
            release_at: "2017-04-12T22:57:37-07:00"
      -
        content_type: question
      -
        url: whatnext.md
        slug: whatnext
  -
    dir: class3
    slug: fiction
    content:
      -
        url: intro.md
        slug: intro
      -
        slug: question1
        content_type: question
      -
        url: extra-pre-reading.md
        slug: prereading
      -
        url: class.md
        slug: liveclass
        schedule:
          -
            release_at: "2017-04-15T10:57:37+01:00"
            leadhub: true
            hub_id: "ams"
      -
        slug: question2
        content_type: question
      -
        url: extended.md
        slug: extended
      -
        url: deepdive.md
        slug: deepdive
      -
        slug: question3
        content_type: question
      -
        url: webinar.md
        slug: webinar
        schedule:
          -
            release_at: "2017-04-17T22:57:37-07:00"
      -
        content_type: question
      -
        url: whatnext.md
        slug: whatnext
  -
    dir: class4
    slug: fact
    content:
      -
        url: intro.md
        slug: intro
      -
        slug: question1 
        content_type: question
      -
        url: extra-pre-reading.md
        slug: prereading
      -
        url: class.md
        slug: liveclass
        schedule:
          -
            release_at: "2017-04-20T10:57:37+01:00"
            leadhub: true
            hub_id: "ams"
      -
        slug: question2
        content_type: question
      -
        url: extended.md
        slug: extended
      -
        url: deepdive.md
        slug: deepdive
      -
        slug: question3
        content_type: question
      -
        url: webinar.md
        slug: webinar
        schedule:
          -
            release_at: "2017-04-22T22:57:37-07:00"
      -
        content_type: question
      -
        url: whatnext.md
        slug: whatnext
  -
    dir: class5
    slug: narrative
    content:
      -
        url: intro.md
        slug: intro
      -
        slug: question1
        content_type: question
      -
        url: extra-pre-reading.md
        slug: prereading
      -
        url: class.md
        slug: liveclass
        schedule:
          -
            release_at: "2017-04-25T10:57:37+01:00"
            leadhub: true
            hub_id: "ams"
      -
        slug: question2
        content_type: question
      -
        url: extended.md
        slug: extended
      -
        url: deepdive.md
        slug: deepdive
      -
        slug: question3
        content_type: question
      -
        url: webinar.md
        slug: webinar
        schedule:
          -
            release_at: "2017-04-28T22:57:37-07:00"
      -
        content_type: question
      -
        url: whatnext.md
        slug: whatnext
  -
    dir: class6
    slug: impact
    content:
      -
        url: intro.md
        slug: intro
      -
        slug: question1
        content_type: question
      -
        url: extra-pre-reading.md
        slug: prereading
      -
        url: class.md
        slug: liveclass
        schedule:
          -
            release_at: "2017-05-01T10:57:37+01:00"
            leadhub: true
            hub_id: "ams"
      -
        slug: question2
        content_type: question
      -
        url: extended.md
        slug: extended
      -
        url: deepdive.md
        slug: deepdive
      -
        slug: question3
        content_type: question
      -
        url: webinar.md
        slug: webinar
        schedule:
          -
            release_at: "2017-05-03T22:57:37-07:00"
      -
        content_type: question
      -
        url: whatnext.md
        slug: whatnext
  -
    dir: class7
    slug: summary
    content:
      -
        url: intro.md
        slug: intro
